### ISSUE TITLE
[Release] v1.0.0 Checklist

### ISSUE THREAD

**Issue by TheCommieAxolotl** [Velocity-Discord/Velocity#4]
# Version 1.0.0 Checklist

## Development
- [x] Update and Installation scripts (Waiting on Public Beta)
- [x] Fix Internal Patch Killing
- [x] Clean up Codebase - Ideally Linting
- [x] i18n
- [x] Reorganize under `src/` directory

## Marketing and PR
- [x] Finish Site
- [x] Site Accessibility
- [x] Publicize Discord Server 

Progress to Public Testing is tracked [here](https://github.com/Velocity-Discord/Velocity/milestone/1)
